export const GET_ALL_COFFEES_REQUEST = 'GET_ALL_COFFEES_REQUEST';
export const GET_ALL_COFFEES_SUCCESS = 'GET_ALL_COFFEES_SUCCESS';
export const GET_ALL_COFFEES_FAIL = 'GET_ALL_COFFEES_FAIL';

export const GET_SINGLE_COFFEE_REQUEST = ' GET_SINGLE_COFFEE_REQUEST';
export const GET_SINGLE_COFFEE_SUCCESS = ' GET_SINGLE_COFFEE_SUCCESS';
export const GET_SINGLE_COFFEE_FAIL = ' GET_SINGLE_COFFEE_FAIL';
